"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { Dialog } from "@/components/crm/Dialog";
import { inviteAdminUserAction } from "@/features/admin-users/actions";
import { ADMIN_USERS_INITIAL } from "@/features/admin-users/action-state";
import type { AdminUserRow } from "@/features/admin-users/read";
import type { RoleCatalogue } from "@/server/authz/role-catalogue";
export function UsersPage({ rows, catalogue, loadError }: { rows: readonly AdminUserRow[]; catalogue: RoleCatalogue; loadError: string | null }) {
 const [open,setOpen]=useState(false); const [operationId,setOperationId]=useState(""); const [state,action,pending]=useActionState(inviteAdminUserAction,ADMIN_USERS_INITIAL);
 const [tab, setTab] = useState<"users" | "roles">("users");
 const openInvite=()=>{ setOperationId(crypto.randomUUID()); setOpen(true); }; const closeInvite=()=>{ setOpen(false); setOperationId(""); };
 return <section className="flex flex-col gap-5 p-6" aria-labelledby="users-heading"><div className="flex items-center justify-between"><h1 id="users-heading" className="text-2xl font-semibold">Användare &amp; roller</h1>{tab === "users" && <button onClick={openInvite} className="rounded-md bg-blue-700 px-4 py-2 text-sm font-medium text-white">Bjud in användare</button>}</div><div role="tablist" aria-label="Användare och roller"><button role="tab" aria-selected={tab === "users"} onClick={() => setTab("users")}>Användare</button><button role="tab" aria-selected={tab === "roles"} onClick={() => setTab("roles")}>Roller</button></div>{loadError&&<p role="alert">{loadError}</p>}{tab === "users" ? <><p className="text-sm text-zinc-600">När en användare inaktiveras eller avslutas tas åtkomsten bort för detta företag. Historiken behålls.</p><ul className="divide-y rounded border">{rows.map(r=><li key={r.id} className="flex justify-between p-3"><Link href={`/admin/users/${r.id}`}>{r.email ?? "Inväntar inbjuden användare"}</Link><span>{r.status} · {r.roles.join(", ")}</span><Link href={`/admin/users/${r.id}`}>Händelser</Link></li>)}</ul></> : <div><p className="mb-3 text-sm text-zinc-600">{catalogue.arbetsledareGuidance}</p><div className="grid gap-3 md:grid-cols-2">{catalogue.roles.map(role => <article key={role.role} className="rounded border p-4"><h2 className="font-semibold">{role.label}</h2><p className="text-sm">{role.description}</p><p className="mt-2">{role.activeMemberLabel}: {role.activeMemberCount}</p><ul className="mt-2 text-sm">{role.grants.map(grant => <li key={`${grant.module}:${grant.capability}`}>{grant.moduleLabel} ({grant.wave}) · {grant.capability}</li>)}</ul>{role.sensitiveEntitlements.length > 0 && <p className="mt-2 text-sm">Känsliga fält: {role.sensitiveEntitlements.join(", ")}</p>}</article>)}</div></div>}<Dialog open={open} onClose={closeInvite} title="Bjud in användare" busy={pending}><form action={action} className="flex flex-col gap-3"><input type="hidden" name="operationId" value={operationId}/><label>E-post<input name="email" type="email" required className="ml-2 border" /></label><fieldset><legend>Roller</legend>{catalogue.roles.map(({role,label})=><label className="mr-3" key={role}><input name="roles" type="checkbox" value={role}/>{label}</label>)}</fieldset>{state.status!=="idle"&&<p role={state.status==="error"?"alert":"status"}>{state.message}</p>}<button disabled={pending || !operationId} className="rounded bg-blue-700 px-3 py-2 text-white">{pending?"Skickar…":"Skicka inbjudan"}</button></form></Dialog></section>;
}
